import CryptoKit
import Foundation
import RemotePiProtocol

// RemotePiCrypto — Ed25519 over CryptoKit, plus the Base64 coercions the wire
// demands.
//
// Everything in this module exists to satisfy three foreign implementations
// byte-for-byte:
//
//   relay/src/auth/challenge.rs      ed25519-dalek, verifies our `auth.sig`
//   pi-extension/src/pairing/crypto  @noble/ed25519 v3, verifies mesh blobs
//   app/lib/**                       package:cryptography, the client we replace
//
// Ed25519 (RFC 8032, PureEdDSA) is deterministic, so "compatible" here is not a
// judgement call: the same 32-byte seed over the same message must produce the
// same 64 signature bytes in all four stacks. `Tests/RemotePiCryptoTests`
// pins that against the RFC 8032 vectors *and* against signatures generated by
// the pi-extension's own @noble/ed25519 build.

/// Ed25519 signing over CryptoKit's `Curve25519.Signing`.
///
/// Wraps a 32-byte seed. `Curve25519.Signing.PrivateKey.rawRepresentation`
/// *is* that seed, which is the same 32 bytes the pi-extension and the relay
/// call an Ed25519 private key — so a key generated here and a key generated
/// by `@napi-rs/keyring` are interchangeable at rest.
///
/// Used for all three keys in the product's identity table (Owner-key,
/// App-key, and — on the Mac, not here — the Pi-key).
public struct Ed25519Signer: Signer {
    private let privateKey: Curve25519.Signing.PrivateKey

    /// The public half, as the relay's peer id.
    public let publicKey: PeerID

    /// Wraps an existing seed, e.g. one loaded from the Keychain.
    ///
    /// Throws when `seed` is not exactly 32 valid bytes rather than silently
    /// deriving a different identity.
    public init(seed: Data) throws {
        let key = try Curve25519.Signing.PrivateKey(rawRepresentation: seed)
        guard let peer = PeerID(rawValue: key.publicKey.rawRepresentation) else {
            throw CryptoError.invalidKeyLength(key.publicKey.rawRepresentation.count)
        }
        self.privateKey = key
        self.publicKey = peer
    }

    /// Generates a fresh keypair. Used for the Owner-key on first launch and
    /// for the ephemeral App-key at the start of each pairing attempt.
    public init() throws {
        let key = Curve25519.Signing.PrivateKey()
        guard let peer = PeerID(rawValue: key.publicKey.rawRepresentation) else {
            throw CryptoError.invalidKeyLength(key.publicKey.rawRepresentation.count)
        }
        self.privateKey = key
        self.publicKey = peer
    }

    /// The 32-byte seed. Secret: persist it through ``KeyStore`` and nowhere
    /// else — never a log, never a `Codable` payload, never a UserDefaults key.
    public var seed: Data { privateKey.rawRepresentation }

    /// Signs the **raw bytes** of `message`.
    ///
    /// CryptoKit's Ed25519 is PureEdDSA: it hashes internally and takes no
    /// context/domain-separation string. That matters because the relay's
    /// `verify_auth` calls `vk.verify(nonce, &sig)` on the *raw* 32 nonce bytes
    /// (`relay/src/auth/challenge.rs:76-89`) — prefixing anything here, or
    /// pre-hashing, produces a signature that verifies nowhere and fails with
    /// an unadorned socket close that carries no diagnosis (spec 62-03 §1.6 F7).
    public func signature(for message: Data) throws -> Data {
        try privateKey.signature(for: message)
    }
}

/// Verifies an Ed25519 signature made by `peer`.
///
/// Used on the `mesh_versions` blob (the client re-verifies rather than
/// trusting the relay's word that a blob is authentic) and anywhere else a
/// signed artifact arrives from outside.
///
/// Returns `false` — never throws — for a malformed key or a malformed
/// signature, because every caller's response to "this did not verify" is the
/// same regardless of *why*, and an error path here invites a `try?` that
/// swallows the distinction between "invalid" and "valid".
public func verifyEd25519(
    signature: Data,
    of message: Data,
    by peer: PeerID
) -> Bool {
    guard
        let key = try? Curve25519.Signing.PublicKey(rawRepresentation: peer.rawValue)
    else { return false }
    return key.isValidSignature(signature, for: message)
}

public enum CryptoError: Error, Sendable, Hashable {
    case invalidKeyLength(Int)
    /// The Keychain refused the operation. `status` is an `OSStatus`.
    case keychain(status: Int32)
    /// A read succeeded but returned something that is not a 32-byte seed.
    case corruptStoredKey
}

/// Marker thrown by a scaffolded body that has not been implemented yet.
///
/// Every occurrence is a work item. There should be none of these left when
/// the client ships; `grep -r notImplemented Sources` is the checklist.
///
/// (Kept in this module because `RemotePiTransport` and `RemotePiPairing`
/// reference it by this name — `RemotePiPairing` even typealiases it. Moving
/// or renaming it breaks their scaffolds.)
public struct ScaffoldError: Error, Sendable, Hashable, CustomStringConvertible {
    public let symbol: String
    public init(notImplemented symbol: String) { self.symbol = symbol }
    public static func notImplemented(_ symbol: String) -> ScaffoldError {
        ScaffoldError(notImplemented: symbol)
    }
    public var description: String { "\(symbol) is not implemented yet" }
}

/// Lowercase hex SHA-256 of `data`.
///
/// The mesh endpoints (`/mesh/<hash>`) key on the digest of the **32 raw
/// Owner-key bytes** — hashing the Base64 text instead produces a URL the
/// relay will answer with an empty membership rather than an error, which is
/// the worst possible failure shape. Use ``meshPathHash(for:)`` rather than
/// calling this with whatever string is at hand.
public func sha256Hex(_ data: Data) -> String {
    SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
}
