import Foundation
import XCTest

@testable import RemotePiCrypto
@testable import RemotePiProtocol

/// Proves CryptoKit's Ed25519 is the same Ed25519 the relay and the Pi use.
///
/// Every assertion here compares against bytes produced *outside* Swift:
/// RFC 8032's own vectors, and signatures generated by the pi-extension's
/// `@noble/ed25519` build. See `WireVectors.swift` for provenance.
final class Ed25519VectorTests: XCTestCase {

    /// RFC 8032 §7.1: key derivation is exact, and the standard's published
    /// signatures verify here.
    ///
    /// **Not asserted: that we reproduce those signature bytes.** CryptoKit's
    /// `Curve25519.Signing` is *hedged* — it mixes fresh randomness into the
    /// nonce, so signing the same message twice with the same key yields two
    /// different 64-byte signatures (pinned by
    /// ``testCryptoKitSignaturesAreHedgedNotDeterministic``). Both are valid
    /// Ed25519 signatures and both verify everywhere; only the textbook
    /// determinism of RFC 8032 is gone.
    ///
    /// This matters beyond this file: **no test, golden file, or e2e harness
    /// anywhere in this client may compare a `sig` string for equality.** The
    /// interop property to assert is always "verifies", in whichever direction
    /// is under test.
    func testRFC8032VectorsDeriveKeysAndVerify() throws {
        for vector in WireVectors.rfc8032 {
            let signer = try Ed25519Signer(seed: WireVectors.data(hex: vector.seed))

            XCTAssertEqual(
                WireVectors.hex(signer.publicKey.rawValue),
                vector.publicKey,
                "public key derivation diverged for seed \(vector.seed.prefix(8))"
            )

            let message = WireVectors.data(hex: vector.message)
            XCTAssertTrue(
                verifyEd25519(
                    signature: WireVectors.data(hex: vector.signature),
                    of: message,
                    by: signer.publicKey
                ),
                "the RFC's own signature did not verify for seed \(vector.seed.prefix(8))"
            )
            // Our own signature over the same message must verify too.
            let ours = try signer.signature(for: message)
            XCTAssertEqual(ours.count, 64)
            XCTAssertTrue(verifyEd25519(signature: ours, of: message, by: signer.publicKey))
        }
    }

    /// Documents the hedging, because it is surprising and because a future
    /// reader *will* try to write an equality assertion against a golden
    /// signature. Both signatures are valid; neither is reproducible.
    func testCryptoKitSignaturesAreHedgedNotDeterministic() throws {
        let signer = try Ed25519Signer(seed: WireVectors.data(hex: WireVectors.nobleSeedHex))
        let message = try XCTUnwrap(Data(base64Encoded: WireVectors.nobleNonceStandard))

        let first = try signer.signature(for: message)
        let second = try signer.signature(for: message)
        XCTAssertNotEqual(first, second, "CryptoKit stopped hedging — see the callers of this fact")
        XCTAssertTrue(verifyEd25519(signature: first, of: message, by: signer.publicKey))
        XCTAssertTrue(verifyEd25519(signature: second, of: message, by: signer.publicKey))
    }

    /// The same seed the pi-extension's `@noble/ed25519` was fed produces the
    /// same public key, in the same spelling the relay stores
    /// (`peer_id = STANDARD_base64(vk.to_bytes())`, `peer.rs:80`).
    func testSeedProducesThePiExtensionsPublicKeySpelling() throws {
        let signer = try Ed25519Signer(seed: WireVectors.data(hex: WireVectors.nobleSeedHex))
        XCTAssertEqual(signer.publicKey.wireValue, WireVectors.noblePubkeyStandard)
        XCTAssertEqual(signer.publicKey.urlSafeValue, WireVectors.noblePubkeyURLSafe)
    }

    /// Interop, both directions, over the same key and message.
    ///
    /// - inbound: a signature made by the pi-extension's `@noble/ed25519`
    ///   verifies here (this is what we do to a fetched mesh blob);
    /// - outbound: a signature made *here* was handed to that same
    ///   `@noble/ed25519` build, which accepted it — see
    ///   ``WireVectors/cryptoKitSigVerifiedByNoble`` for the recorded bytes
    ///   and the command that checked them. Re-verifying them here pins the
    ///   exact signature that was externally validated, which is the closest a
    ///   hermetic test can get to "the relay would have accepted this".
    func testNobleAndCryptoKitAcceptEachOthersSignatures() throws {
        let signer = try Ed25519Signer(seed: WireVectors.data(hex: WireVectors.nobleSeedHex))
        let nonce = try XCTUnwrap(Data(base64Encoded: WireVectors.nobleNonceStandard))

        let foreign = try XCTUnwrap(Data(base64Encoded: WireVectors.nobleAuthSigStandard))
        XCTAssertTrue(verifyEd25519(signature: foreign, of: nonce, by: signer.publicKey))

        let oursThatNobleAccepted = try XCTUnwrap(
            Data(base64Encoded: WireVectors.cryptoKitSigVerifiedByNoble))
        XCTAssertTrue(
            verifyEd25519(signature: oursThatNobleAccepted, of: nonce, by: signer.publicKey))

        // And a freshly hedged one is just as valid.
        XCTAssertTrue(
            verifyEd25519(signature: try signer.signature(for: nonce), of: nonce, by: signer.publicKey)
        )
    }

    /// A CryptoKit key round-trips through its raw seed, which is what the
    /// Keychain stores. `rawRepresentation` is the 32-byte seed — not an
    /// expanded 64-byte "secret key" — so it is interchangeable with the
    /// `randomBytes(32)` the pi-extension persists.
    func testSignerRoundTripsThroughItsSeed() throws {
        let signer = try Ed25519Signer()
        XCTAssertEqual(signer.seed.count, 32)

        let restored = try Ed25519Signer(seed: signer.seed)
        XCTAssertEqual(signer.publicKey, restored.publicKey)

        let message = Data("the relay's 32-byte nonce, decoded".utf8)
        let signature = try restored.signature(for: message)
        XCTAssertTrue(verifyEd25519(signature: signature, of: message, by: signer.publicKey))
        XCTAssertFalse(
            verifyEd25519(signature: signature, of: Data("other".utf8), by: signer.publicKey)
        )
    }

    func testRejectsASeedThatIsNotThirtyTwoBytes() {
        XCTAssertThrowsError(try Ed25519Signer(seed: Data(repeating: 7, count: 31)))
        XCTAssertThrowsError(try Ed25519Signer(seed: Data(repeating: 7, count: 64)))
    }

    /// Verification must answer `false`, never throw and never crash, for
    /// malformed input — a signature arrives from the network and the relay is
    /// not trusted to have checked it.
    func testVerificationFailsClosedOnMalformedSignatures() throws {
        let signer = try Ed25519Signer(seed: WireVectors.data(hex: WireVectors.nobleSeedHex))
        let nonce = try XCTUnwrap(Data(base64Encoded: WireVectors.nobleNonceStandard))
        var signature = try XCTUnwrap(Data(base64Encoded: WireVectors.nobleAuthSigStandard))

        XCTAssertFalse(verifyEd25519(signature: Data(), of: nonce, by: signer.publicKey))
        XCTAssertFalse(
            verifyEd25519(signature: signature.dropLast(), of: nonce, by: signer.publicKey))

        signature[0] ^= 0x01
        XCTAssertFalse(verifyEd25519(signature: signature, of: nonce, by: signer.publicKey))
    }

    /// `/mesh/<hash>` keys on the digest of the raw key bytes. Pinned against
    /// `sha256sum` of a zero-filled 32-byte block, which is a published
    /// constant, plus node's digest of the noble key.
    func testSHA256HexMatchesForeignDigests() throws {
        XCTAssertEqual(
            sha256Hex(Data(repeating: 0, count: 32)),
            "66687aadf862bd776c8fc18b8e9f8e20089714856ee233b3902a591d0d5f2925"
        )
        let owner = try XCTUnwrap(PeerID(base64: WireVectors.noblePubkeyStandard))
        XCTAssertEqual(sha256Hex(owner.rawValue), WireVectors.meshPathHashHex)
    }
}
