import Foundation

/// Test vectors that came from somewhere other than this codebase.
///
/// The rule for this file: **nothing here may be produced by Swift.** A test
/// that checks our encoder against our decoder proves that we are
/// self-consistent, which is exactly the property that was never in doubt. The
/// question is whether we agree with `ed25519-dalek` (the relay),
/// `@noble/ed25519` (the Pi) and `package:cryptography` (the Flutter client we
/// are replacing), and only foreign bytes can answer that.
///
/// Provenance is recorded per vector. Regenerate the `noble*` ones with:
///
/// ```bash
/// node --input-type=module -e '
///   import { createHash } from "node:crypto";
///   import * as ed from "<repo>/pi-extension/node_modules/@noble/ed25519/index.js";
///   ed.hashes.sha512 = (...m) => { const h = createHash("sha512");
///     for (const x of m) h.update(x); return Uint8Array.from(h.digest()); };
///   const seed = Uint8Array.from({length:32}, (_,i)=> i+1);
///   console.log(Buffer.from(ed.getPublicKey(seed)).toString("base64"));
/// '
/// ```
enum WireVectors {
    // MARK: - RFC 8032 §7.1 — the standard's own Ed25519 vectors
    //
    // Re-verified against the pi-extension's own @noble/ed25519 v3.1.0 build
    // before being pinned here.
    //
    // NOTE: these are used for *key derivation* equality and for *verifying*
    // the published signatures — never for asserting that we reproduce them.
    // CryptoKit hedges its Ed25519 nonce, so it does not emit RFC 8032's
    // deterministic bytes. See `Ed25519VectorTests` for the full explanation.

    /// (seed, public key, message, signature) — all hex.
    static let rfc8032: [(seed: String, publicKey: String, message: String, signature: String)] = [
        (
            seed: "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60",
            publicKey: "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
            message: "",
            signature: "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e0652249015"
                + "55fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b"
        ),
        (
            seed: "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb",
            publicKey: "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
            message: "72",
            signature: "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69d"
                + "a085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00"
        ),
        (
            seed: "c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7",
            publicKey: "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025",
            message: "af82",
            signature: "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3a"
                + "c18ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a"
        ),
    ]

    // MARK: - Generated by the pi-extension's own @noble/ed25519 v3.1.0
    //
    // seed  = bytes 0x01…0x20
    // nonce = bytes (i * 7 + 3) & 0xff, i in 0..<32   (stands in for the
    //         relay's 32 random challenge bytes)

    static let nobleSeedHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"

    /// `hello.pubkey` / `Envelope.peer` spelling: standard, padded.
    static let noblePubkeyStandard = "ebVWLo/mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ="
    /// QR (`remotepi://pair?epk=…`) and storage-key spelling: url-safe, unpadded.
    static let noblePubkeyURLSafe = "ebVWLo_mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ"

    /// Exactly as a relay `{"type":"challenge","nonce":…}` frame carries it:
    /// standard Base64, padded, 44 characters (`challenge.rs:46-51`).
    static let nobleNonceStandard = "AwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dw="

    /// The `sig` of the matching `{"type":"auth","sig":…}` frame: Ed25519 over
    /// the 32 **raw** nonce bytes, standard Base64, padded, 88 characters.
    static let nobleAuthSigStandard =
        "XmZ/zD8e6QxJlW4LkDO6wbYpEcsMb2ZKDTIPMkZPHmCF0Ic7BJIjOvDywzD034wL7jyWXAPln7JnwENbaNAvDw=="

    /// The **outbound** half of the interop check: a signature produced by
    /// CryptoKit over the same key and nonce, which `@noble/ed25519` then
    /// accepted.
    ///
    /// It differs from ``nobleAuthSigStandard`` and always will — CryptoKit
    /// hedges its Ed25519 nonce, so it never reproduces RFC 8032's
    /// deterministic bytes. Both signatures are valid; only "verifies" is a
    /// testable property. Recorded here because the check itself is not
    /// hermetic:
    ///
    /// ```bash
    /// node --input-type=module -e '
    ///   import { createHash } from "node:crypto";
    ///   import * as ed from "<repo>/pi-extension/node_modules/@noble/ed25519/index.js";
    ///   ed.hashes.sha512 = (...m) => { const h = createHash("sha512");
    ///     for (const x of m) h.update(x); return Uint8Array.from(h.digest()); };
    ///   const seed  = Uint8Array.from({length:32}, (_,i)=> i+1);
    ///   const nonce = Uint8Array.from({length:32}, (_,i)=> (i*7+3)&0xff);
    ///   console.log(ed.verify(new Uint8Array(Buffer.from(process.argv[1], "base64")),
    ///                         nonce, ed.getPublicKey(seed)));
    /// ' "<the base64 below>"        # → true
    /// ```
    static let cryptoKitSigVerifiedByNoble =
        "htNfuziMzpHNpll131MyU6BjwSjrfW7rCSoHpfoeMh4wEp3Z0MBnFsDUPGKgR2RL0+rv9sVlivNNK2/G3EqCAA=="

    // MARK: - Membership blob (spec 62-04 §10)
    //
    // The canonical JSON is the example from the spec, with `owner_pk` set to
    // the noble key above and `remote_epk` to the pi-extension test fixture
    // `(i * 17 + 11) & 0xff`. The signature was produced by @noble over these
    // exact bytes.

    static let meshCanonicalJSON = """
        {"issued_at":1780000000000,"members":[{"nickname":"casa",\
        "paired_at":"2026-08-25T12:34:56.789Z",\
        "relay_url":"https://relay.remotepi.dev",\
        "remote_epk":"CxwtPk9gcYKTpLXG1+j5ChssPU5fcIGSo7TF1uf4CRo="}],\
        "owner_pk":"ebVWLo/mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ=","version":8}
        """

    static let meshSigStandard =
        "8qzlJps9WRQAXcSTVmDhyK0bWPam6YiUFFGUAdal4tHLjxp/vx6m+/5yLlNKjKT6QnKGAJkCjTNO+ahdn76VBA=="

    /// `POST /mesh/<hash>` — `sha256sum` of the 32 raw Owner-key bytes,
    /// computed by node's `createHash("sha256")`.
    static let meshPathHashHex =
        "65b60673d6ed884bf01c2c222d82ada0740f29ac3355d6a925c81f17f47a27b8"

    /// `(i * 17 + 11) & 0xff` — the pi-extension's `PI_ONE_BYTES` fixture
    /// (`pi-extension/src/mesh/verify.test.ts:6-9`).
    static let piOneStandard = "CxwtPk9gcYKTpLXG1+j5ChssPU5fcIGSo7TF1uf4CRo="

    // MARK: - epk spellings
    //
    // From `app/test/transport/epk_encoding_test.dart` (the Dart client's own
    // fixture) and `relay/src/identity.rs`'s test module.

    static let dartEPKURLSafe = "Bz02uLiwrmQZ0S8qiwtFJAt0KzUvrgepYO_oMQ6yyQE"
    static let dartEPKStandard = "Bz02uLiwrmQZ0S8qiwtFJAt0KzUvrgepYO/oMQ6yyQE="

    /// 32 × 0xfb, the relay's `STANDARD_KEY` / `URL_SAFE_KEY` fixtures. Chosen
    /// there because the byte pattern exercises `+`, `/`, `-` and `_` in a
    /// single key.
    static let relayKeyStandard = "+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/s="
    static let relayKeyStandardNoPad = "+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/s"
    static let relayKeyURLSafe = "-_v7-_v7-_v7-_v7-_v7-_v7-_v7-_v7-_v7-_v7-_s="
    static let relayKeyURLSafeNoPad = "-_v7-_v7-_v7-_v7-_v7-_v7-_v7-_v7-_v7-_v7-_s"

    // MARK: - helpers

    static func data(hex: String) -> Data {
        var bytes = [UInt8]()
        bytes.reserveCapacity(hex.count / 2)
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            bytes.append(UInt8(hex[index..<next], radix: 16)!)
            index = next
        }
        return Data(bytes)
    }

    static func hex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }
}
